#!/usr/bin/env bash
# match_methodologies.sh — Trigger-aware methodology selection (Tier 1 #2, v1.20.0)
#
# Reads the YAML frontmatter of every methodology/M*.md template and tests its
# trigger against the audit target:
#   trigger_type: code     -> grep -riEl "$trigger_grep" over the source dir
#   trigger_type: artifact -> find "$trigger_glob" in the project root (depth 2)
#   trigger_type: process  -> always applicable at the stated pipeline event
#
# Emits $OUT/applicable-methodologies.md for the session-start preflight.
#
# Usage:
#   scripts/match_methodologies.sh --src ./contracts [--root .] [--lang evm] [--out $SCRATCHPAD]
#
#   --src   source dir of the audit target (required)
#   --root  project root for artifact globs (default: parent of --src, else .)
#   --lang  detected language (evm|solana|stellar|aptos|sui|cpp|go) — filters
#           templates whose trigger_languages excludes it. Omit = no filter.
#   --out   output dir (default: .)
set -u

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="" ROOT="" LANG_FILTER="" OUT="."

while [ $# -gt 0 ]; do
  case "$1" in
    --src)  SRC="$2"; shift 2 ;;
    --root) ROOT="$2"; shift 2 ;;
    --lang) LANG_FILTER="$2"; shift 2 ;;
    --out)  OUT="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

[ -n "$SRC" ] || { echo "usage: match_methodologies.sh --src DIR [--root DIR] [--lang L] [--out DIR]" >&2; exit 1; }
[ -d "$SRC" ] || { echo "error: --src '$SRC' is not a directory" >&2; exit 1; }
[ -n "$ROOT" ] || ROOT="$(dirname "$SRC")"
[ -d "$ROOT" ] || ROOT="."
mkdir -p "$OUT"
REPORT="$OUT/applicable-methodologies.md"

# Extract one frontmatter field value (strips surrounding quotes/brackets).
fm_field() { # $1=frontmatter text  $2=field name
  printf '%s\n' "$1" | sed -n "s/^$2:[[:space:]]*//p" | head -1 \
    | sed -e 's/^"//' -e 's/"$//' -e 's/^\[//' -e 's/\]$//'
}

GREP_EXCLUDES=(--exclude-dir=.git --exclude-dir=target --exclude-dir=node_modules
               --exclude-dir=out --exclude-dir=build --exclude-dir=cache
               --exclude-dir=lib --exclude-dir=artifacts)

fired_code="" fired_artifact="" process_rows="" not_fired="" skipped="" warned=""

for f in "$SKILL_DIR"/methodology/M*.md; do
  base="$(basename "$f")"
  # Frontmatter = lines between the first two '---' fences (must start at line 1).
  head -1 "$f" | grep -q '^---$' || { warned="$warned- $base: no frontmatter (run Tier 1 #2 retrofit)\n"; continue; }
  fm="$(awk 'NR==1{next} /^---$/{exit} {print}' "$f")"

  id="$(fm_field "$fm" id)"; [ -n "$id" ] || id="$base"
  ttype="$(fm_field "$fm" trigger_type)"
  langs="$(fm_field "$fm" trigger_languages)"

  # Language filter: skip when a filter is set and the template names specific
  # languages that don't include it.
  if [ -n "$LANG_FILTER" ] && [ -n "$langs" ] && ! printf '%s' "$langs" | grep -qiE "(all|$LANG_FILTER)"; then
    skipped="$skipped| $id | $base | languages: $langs |\n"
    continue
  fi

  case "$ttype" in
    code)
      pat="$(fm_field "$fm" trigger_grep)"
      if [ -z "$pat" ]; then warned="$warned- $base: trigger_type=code but no trigger_grep\n"; continue; fi
      matches="$(grep -riEl "${GREP_EXCLUDES[@]}" -- "$pat" "$SRC" 2>/dev/null)"
      rc=$?
      if [ $rc -ge 2 ]; then warned="$warned- $base: trigger_grep failed to compile: $pat\n"; continue; fi
      if [ -n "$matches" ]; then
        n="$(printf '%s\n' "$matches" | wc -l | tr -d ' ')"
        sample="$(printf '%s\n' "$matches" | head -3 | tr '\n' ' ')"
        fired_code="$fired_code| $id | $base | $n file(s) | $sample|\n"
      else
        not_fired="$not_fired| $id | $base | code | no grep match |\n"
      fi
      ;;
    artifact)
      glob="$(fm_field "$fm" trigger_glob)"
      if [ -z "$glob" ]; then warned="$warned- $base: trigger_type=artifact but no trigger_glob\n"; continue; fi
      hits=""
      for g in $glob; do
        h="$(find "$ROOT" -maxdepth 2 -name "$g" 2>/dev/null | head -3)"
        [ -n "$h" ] && hits="$hits $h"
      done
      if [ -n "$hits" ]; then
        fired_artifact="$fired_artifact| $id | $base |$hits |\n"
      else
        not_fired="$not_fired| $id | $base | artifact | no file matching $glob |\n"
      fi
      ;;
    process)
      ev="$(fm_field "$fm" trigger_event)"
      process_rows="$process_rows| $id | $base | ${ev:-unspecified} |\n"
      ;;
    *)
      warned="$warned- $base: unknown trigger_type '$ttype'\n"
      ;;
  esac
done

{
  echo "# Applicable Methodologies — trigger-aware selection"
  echo
  echo "> Generated by scripts/match_methodologies.sh"
  echo "> src: $SRC | root: $ROOT | lang filter: ${LANG_FILTER:-none}"
  echo
  echo "## FIRED — code-triggered (load these templates FIRST)"
  echo
  if [ -n "$fired_code" ]; then
    echo "| ID | Template | Matches | Sample files |"
    echo "|----|----------|---------|--------------|"
    printf '%b' "$fired_code"
  else
    echo "_none fired_"
  fi
  echo
  echo "## FIRED — artifact-triggered"
  echo
  if [ -n "$fired_artifact" ]; then
    echo "| ID | Template | Artifact(s) |"
    echo "|----|----------|-------------|"
    printf '%b' "$fired_artifact"
  else
    echo "_none fired_"
  fi
  echo
  echo "## Always-on / event-driven (process methodologies)"
  echo
  echo "| ID | Template | Apply at |"
  echo "|----|----------|----------|"
  printf '%b' "$process_rows"
  echo
  echo "## Not fired"
  echo
  if [ -n "$not_fired" ]; then
    echo "| ID | Template | Type | Reason |"
    echo "|----|----------|------|--------|"
    printf '%b' "$not_fired"
  else
    echo "_none_"
  fi
  if [ -n "$skipped" ]; then
    echo
    echo "## Skipped by language filter"
    echo
    echo "| ID | Template | Languages |"
    echo "|----|----------|-----------|"
    printf '%b' "$skipped"
  fi
  if [ -n "$warned" ]; then
    echo
    echo "## Warnings"
    echo
    printf '%b' "$warned"
  fi
} > "$REPORT"

echo "wrote $REPORT"
